version: '3'
services:
    apache:
        build: ./apache
        container_name: meg_apache
        ports:
          - 8089:80
        volumes:
          - ./config/vhosts:/etc/apache2/sites-enabled
          - ../src:/home/wwwroot/wc
        depends_on:
          - php

    mysql:
        image: mysql:8.0
        command : --default-authentication-plugin=mysql_native_password
        container_name: meg_mysql
        restart: always
        ports:
            - 3308:3306
        volumes:
            - ./data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_moreezgo
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            
    php:
        build: ./php
        container_name: meg_php
        volumes:
            - ../src:/home/wwwroot/wc
        environment:
            - maildev_host=bit_maildev
        links:
            - mysql:db
        ports:
            - 9001:9001
            - 8448:8448
            - 8001:8000
        depends_on:
            - maildev
            - mysql 

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: meg_phpmyadmin
        ports:
            - 8081:80
        links:
            - mysql
        environment:
            PMA_HOST: mysql       
  

    maildev:
        image: djfarrelly/maildev
        container_name: meg_maildev
        ports:
            - 8002:80                         
 
